# Generated by Django 3.1.5 on 2021-03-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageDictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='dictionarypair',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='dictionarypair',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dictionarypair',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
    ]
