# Generated by Django 3.1.5 on 2021-03-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languageDictionary', '0002_auto_20210330_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionarypair',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='languageDictionary.language'),
            preserve_default=False,
        ),
    ]
