# Generated by Django 3.1.5 on 2021-03-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageDictionary', '0003_dictionarypair_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionarypair',
            name='eng',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dictionarypair',
            name='rus',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
