# Generated by Django 3.1.5 on 2021-04-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languageDictionary', '0006_place_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('languageDictionary.place',),
        ),
    ]
